Add tests for pure functions
Hope1226/To-Do-List pull request #5
Opened 2021-11-05 15:44 UTC by Hope1226

In this feature branch I:
- Added test for updateStaus function
- Added test for updateLocalStr function 
- Added test for updateDisplay 
- Mocked DOM using JSDOM

2021-11-05 17:05 UTC, mikethreels requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-05 17:45 UTC, Hope1226 commented on src/updateStatus.test.js
> +});
Hi thanks for your valuable feedback, it is highly appreciated, I have only two functions left to be tested addTask() as well as removeCompleted, I left them for the second part of this project considering their complexity. For the first part, I tried to choose as pure functions as possiable. Do you still think I need to write a test for add and delete functions? in that case I won't have anything for the second pull request.

2021-11-05 18:47 UTC, henatan99 commented on src/updateDisplay.test.js
> +});
This issue has been addressed well. Nice job! :pray:

2021-11-05 18:53 UTC, henatan99 requested changes
Hi @Hope1226 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-05 18:53 UTC, henatan99 commented on src/app.test.js
> +  test('Update display', () => {
- [ ] It is good you add some tests for methods related to updating the todo. But as it was mentioned by the previous reviewer, testing the methods related to adding and removing to-do item are mandatory for this milestone. While what you did here are optional tests but you can still keep them. :pray: Kindly read the [project requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/tests_1.md) carefully.

2021-11-06 00:41 UTC, rloterh commented on src/app.test.js
> +  test('Update display', () => {
This issue is well resolved! ✔️

2021-11-06 00:42 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Ibrohim & Hope, 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer(s). There is nothing else to say other than... it's time to merge it 🍾 :shipit:.
Congratulations! 🎉🥂

<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have no more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-06 00:57 UTC, merged